[build]
target = "web/index.html"
public_url = "/web/dist/"

[watch]
ignore = ["web/dist_ts"]

[[hooks]]
stage = "pre_build"
command = "npm"
command_arguments = ["--prefix", "web", "run", "build:ts"]
