[package]
name = "nepl-web"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
nepl-core = { path = "../nepl-core" }
wasmprinter = "0.2"
web-sys = { version = "0.3", features = ["console"] }
js-sys = "0.3"

[workspace]
